
name: Pipeline-CI-CD

on:

  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Installing gatsby & npm
        working-directory: ./web
        run: |
          ls -la
          npm install
        
      - name: Setup npm
        working-directory: ./web
        run: |
          npm run setup -- --spaceId=${{ secrets.CONTENTFUL_SPACE_ID }} --managementToken=${{ secrets.CONTENTFUL_MANAGEMENT_KEY }} --accessToken=${{ secrets.CONTENTFUL_DELIVERY_KEY }}
          ls -la
        
      - name: Build the artifact
        working-directory: ./web
        run: |
          npm run build
          ls web
          
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web/public
