
name: Pipeline-CI-CD

on:

  push:
    branches: 
      - master
      - Solution
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Installing gatsby & npm
        working-directory: ./web
        run: |
          ls -la
          npm install
          npm install -g gatsby-cli
        
      - name: Build the artifact
        working-directory: ./web
        run: |
          npm run setup -- --spaceId=${{ secrets.CONTENTFUL_SPACE_ID }} --managementToken=${{ secrets.CONTENTFUL_MANAGEMENT_KEY }} --accessToken=${{ secrets.CONTENTFUL_DELIVERY_KEY }}
          ls -la
