
name: Pipeline-CI-CD

on:

  push:
    branches: 
      - master
      - Solution
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_KEY }}
      CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_KEY }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Installing gatsby
        working-directory: ./web
        run: |
          ls -la
          npm install
          npm install -g gatsby-cli
          gatsby --version
        
        
